const express = require("express");
const router = express.Router();
const runningGroupMemberController = require("../controllers/running_group_member");
router.get("/", runningGroupMemberController.getAll);
router.get("/create/", runningGroupMemberController.getForm);
router.post("/create/", runningGroupMemberController.create);
router.post("/update/:id", runningGroupMemberController.update);
router.get("/showbyid/:id", runningGroupMemberController.showById);
router.post("/delete/:id", runningGroupMemberController.delete);
module.exports = router;
