const express = require("express");
const router = express.Router();
const userController = require("../controllers/user");
router.get("/", userController.getAll);
router.get("/create/", userController.getForm);
router.post("/create/", userController.create);
router.post("/:id", userController.update);
router.get("/:id", userController.showById);
router.delete("/delete/:id", userController.delete);
module.exports = router;
